
$(document).ready(function() {

    const lugo = [
        "Abadín",
        "Alfoz",
        "Antas de Ulla",
        "Baleira",
        "Baralla",
        "Barreiros",
        "Becerreá",
        "Begonte",
        "Bóveda",
        "Burela",
        "Carballedo",
        "Castro de Rei",
        "Castroverde",
        "Cervantes",
        "Cervo",
        "Chantada",
        "Corgo (O)",
        "Cospeito",
        "Folgoso do Courel",
        "Fonsagrada (A)",
        "Foz",
        "Friol",
        "Guitiriz",
        "Guntín",
        "Incio (O)",
        "Láncara",
        "Lourenzá",
        "Lugo",
        "Meira",
        "Mondoñedo",
        "Monforte de Lemos",
        "Monterroso",
        "Muras",
        "Navia de Suarna",
        "Negueira de Muñiz",
        "Nogais (As)",
        "Ourol",
        "Outeiro de Rei",
        "Palas de Rei",
        "Pantón",
        "Paradela",
        "Pastoriza (A)",
        "Páramo (O)",
        "Pedrafita do Cebreiro",
        "Pobra do Brollón (A)",
        "Pol",
        "Pontenova (A)",
        "Portomarín",
        "Quiroga",
        "Rábade",
        "Ribadeo",
        "Ribas de Sil",
        "Ribeira de Piquín",
        "Riotorto",
        "Samos",
        "Sarria",
        "Saviñao (O)",
        "Sober",
        "Taboada",
        "Xermade",
        "Xove",
        "Trabada",
        "Triacastela",
        "Valadouro (O)",
        "Vicedo (O)",
        "Vilalba",
        "Viveiro"
    ];

    const pontevedra = [
        "Agolada",
        "Arbo",
        "Baiona",
        "Barro",
        "Bueu",
        "Caldas de Reis",
        "Cambados",
        "Campo Lameiro",
        "Cangas",
        "Cañiza (A)",
        "Catoira",
        "Cerdedo",
        "Cotobade",
        "Covelo",
        "Crecente",
        "Cuntis",
        "Dozón",
        "Estrada (A)",
        "Forcarei",
        "Fornelos de Montes",
        "Gondomar",
        "Grove (O)",
        "Guarda (A)",
        "Illa de Arousa (A)",
        "Lalín",
        "Lama (A)",
        "Marín",
        "Meaño",
        "Meis",
        "Moaña",
        "Mondariz",
        "Mondariz-Balneario",
        "Moraña",
        "Mos",
        "Neves (As)",
        "Nigrán",
        "Oia",
        "Pazos de Borbén",
        "Poio",
        "Ponte Caldelas",
        "Ponteareas",
        "Pontecesures",
        "Pontevedra",
        "Porriño (O)",
        "Portas",
        "Redondela",
        "Ribadumia",
        "Rodeiro",
        "Rosal (O)",
        "Salceda de Caselas",
        "Salvaterra de Miño",
        "Sanxenxo",
        "Silleda",
        "Soutomaior",
        "Tomiño",
        "Tui",
        "Valga",
        "Vigo",
        "Vila de Cruces",
        "Vilaboa",
        "Vilagarcía de Arousa",
        "Vilanova de Arousa"
    ];

    const orense = [
        "Allariz",
        "Amoeiro",
        "Arnoia (A)",
        "Avión",
        "Baltar",
        "Bande",
        "Baños de Molgas",
        "Barbadás",
        "Barco de Valdeorras (O)",
        "Beade",
        "Beariz",
        "Blancos (Os)",
        "Boborás",
        "Bola (A)",
        "Bolo (O)",
        "Calvos de Randín",
        "Carballeda de Avia",
        "Carballeda de Valdeorras",
        "Carballiño (O)",
        "Cartelle",
        "Castrelo de Miño",
        "Castrelo do Val",
        "Castro Caldelas",
        "Celanova",
        "Cenlle",
        "Chandrexa de Queixa",
        "Coles",
        "Cortegada",
        "Cualedro",
        "Entrimo",
        "Esgos",
        "Gomesende",
        "Gudiña (A)",
        "Irixo (O)",
        "Larouco",
        "Laza",
        "Leiro",
        "Lobeira",
        "Lobios",
        "Maceda",
        "Manzaneda",
        "Maside",
        "Melón",
        "Merca (A)",
        "Mezquita (A)",
        "Montederramo",
        "Monterrei",
        "Muiños",
        "Nogueira de Ramuín",
        "Oímbra",
        "Ourense",
        "Paderne de Allariz",
        "Padrenda",
        "Parada de Sil",
        "Pereiro de Aguiar (O)",
        "Peroxa (A)",
        "Petín",
        "Piñor",
        "Pobra de Trives (A)",
        "Pontedeva",
        "Porqueira",
        "Punxín",
        "Quintela de Leirado",
        "Rairiz de Veiga",
        "Ramirás",
        "Ribadavia",
        "Riós",
        "Rubiá",
        "Rúa (A)",
        "San Amaro",
        "San Cibrao das Viñas",
        "San Cristovo de Cea",
        "Sandiás",
        "San Xoán de Río",
        "Sarreaus",
        "Taboadela",
        "Teixeira (A)",
        "Toén",
        "Trasmiras",
        "A Veiga",
        "Verea",
        "Verín",
        "Viana do Bolo",
        "Vilamarín",
        "Vilamartín de Valdeorras",
        "Vilar de Barrio",
        "Vilar de Santos",
        "Vilardevós",
        "Vilariño de Conso",
        "Xinzo de Limia",
        "Xunqueira de Ambía",
        "Xunqueira de Espadanedo"
    ];

    const corunha = [
        "Abegondo",
        "Ames",
        "Aranga",
        "Ares",
        "Arteixo",
        "Arzúa",
        "Baña (A)",
        "Bergondo",
        "Betanzos",
        "Boimorto",
        "Boiro",
        "Boqueixón",
        "Brión",
        "Cabana de Bergantiños",
        "Cabanas",
        "Camariñas",
        "Cambre",
        "Capela (A)",
        "Carballo",
        "Cariño",
        "Carnota",
        "Carral",
        "Cedeira",
        "Cee",
        "Cerceda",
        "Cerdido",
        "Cesuras",
        "Coirós",
        "Corcubión",
        "Coristanco",
        "Coruña (A)",
        "Culleredo",
        "Curtis",
        "Dodro",
        "Dumbría",
        "Fene",
        "Ferrol",
        "Fisterra",
        "Frades",
        "Irixoa",
        "Laracha (A)",
        "Laxe",
        "Lousame",
        "Malpica de Bergantiños",
        "Mañón",
        "Mazaricos",
        "Melide",
        "Mesía",
        "Miño",
        "Moeche",
        "Monfero",
        "Mugardos",
        "Muros",
        "Muxía",
        "Narón",
        "Neda",
        "Negreira",
        "Noia",
        "Oleiros",
        "Ordes",
        "Oroso",
        "Ortigueira",
        "Outes",
        "Oza dos Ríos",
        "Paderne",
        "Padrón",
        "Pino (O)",
        "Pobra do Caramiñal (A)",
        "Ponteceso",
        "Pontedeume",
        "Pontes de García Rodríguez (As)",
        "Porto do Son",
        "Rianxo",
        "Ribeira",
        "Rois",
        "Sada",
        "San Sadurniño",
        "Santa Comba",
        "Santiago de Compostela",
        "Santiso",
        "Sobrado",
        "Somozas (As)",
        "Teo",
        "Toques",
        "Tordoia",
        "Touro",
        "Trazo",
        "Val do Dubra",
        "Valdoviño",
        "Vedra",
        "Vilarmaior",
        "Vilasantar",
        "Vimianzo",
        "Zas"
    ];

    
    $('#selectProvincia').change(function () {

        $('#selectPoblacion').empty();

            $('#selectPoblacion').append('<option value="Todas">Todas</option>');

            if($('#selectProvincia').val() == 'Lugo'){

                for(var i=0; i < lugo.length; i++){

                    $('#selectPoblacion').append('<option value="' + lugo[i] + '"> ' + lugo[i] + '</option>');

                }

            }

            if($('#selectProvincia').val() == 'Orense'){

                for(var i=0; i < orense.length; i++){

                    $('#selectPoblacion').append('<option value="' + orense[i] + '"> ' + orense[i] + '</option>');

                }

            }

            if($('#selectProvincia').val() == 'Pontevedra'){

                for(var i=0; i < pontevedra.length; i++){

                    $('#selectPoblacion').append('<option value="' + pontevedra[i] + '"> ' + pontevedra[i] + '</option>');

                }

            }

            if($('#selectProvincia').val() == 'Coruña'){

                for(var i=0; i < corunha.length; i++){

                    $('#selectPoblacion').append('<option value="' + corunha[i] + '"> ' + corunha[i] + '</option>');

                }

            }

    });
    

});


