CREATE TABLE listacursos_backup SELECT * FROM `listacursos`;
ALTER TABLE `listacursos` CHANGE `nombreCurso` `nombreCurso` VARCHAR(1000) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL;
ALTER TABLE `listacursos` ADD `orden` INT NULL DEFAULT '0' AFTER `horasCurso`;

TRUNCATE listacursos;
INSERT INTO `listacursos` (`idCurso`, `nombreCurso`, `tipoCurso`, `horasCurso`) VALUES
(1, 'C1: Actividades CNAE 24', 'TPM', NULL),
(2, 'C2 Actividades CNAE 30.1 Y 33.15: trabajos de construcción, reparación y mantenimiento naval en astilleros y muelles ', 'TPM', NULL),
(4, 'C3: Operarios de trabajos en forja', 'TPM', NULL),
(5, 'C4: Operarios en trabajos de soldadura y oxicorte', 'TPM', NULL),
(6, 'C5: Operarios de máquinas de mecanizado por arranque de viruta', 'TPM', NULL),
(7, 'C6: Operarios de máquinas de mecanizado por abrasión', 'TPM', NULL),
(8, 'C7: Operarios de máquinas de mecanizado por deformación y corte del metal', 'TPM', NULL),
(9, 'C8: Operarios en actividades de tratamientos superficiales de las piezas de metal', 'TPM', NULL),
(10, 'C9: Operarios en actividades de premontaje, montaje, cambio de formato y ensamblaje en fabricas', 'TPM', NULL),
(11, 'C10: Trabajos de carpintería metálica', 'TPM', NULL),
(12, 'C11: Operarios en trabajos de joyería', 'TPM', NULL),
(13, 'C12: Trabajos de mecánica, mantenimiento y reparación de máquinas, equipos industriales y/o equipos electromecánicos (industria aeroespacial….)', 'TPM', NULL),
(14, 'C13: Trabajos en talleres de reparación de vehículos', 'TPM', NULL),
(15, 'C14: Trabajos en instalación, mantenimiento y reparación de equipos informáticos, automatismos y su programación, ordenadores y sus periféricos o dispositivos auxiliares: equipos y tecnologías de telecomunicaciones y de la información de redes de información y datos (TICs)', 'TPM', NULL),
(16, 'C15: Instaladores y reparadores de líneas y equipos eléctricos', 'TPM', NULL),
(17, 'C16: Trabajos de fontanería, instalaciones de calefacción- climatización, instalaciones de agua caliente sanitaria e instalaciones solares térmicas', 'TPM', NULL),
(18, 'C17: Trabajos de mantenimiento, reparación e instalación de ascensores', 'TPM', NULL),
(19, 'C18: Trabajos de aislamiento e impermeabilización', 'TPM', NULL),
(20, 'C19: Trabajos de montaje de estructuras tubulares', 'TPM', NULL),
(21, 'C20: Trabajos de construcción y mantenimiento de vías férreas', 'TPM', NULL),
(22, 'C21: Trabajos de instalaciones, mantenimiento y reparación de infraestructuras de telecomunicaciones (TIC y digitalización)', 'TPM', NULL),
(23, 'C22: Trabajos en gaseoductos y redes de distribución de gases combustibles', 'TPM', NULL),
(24, 'C23: Trabajos de otro tipo de instalaciones tales como instalaciones solares fotovoltaicas o instalaciones eólicas', 'TPM', NULL),
(25, 'C24: Trabajos de recuperación y reciclaje de materias primas secundarias metálicas', 'TPM', NULL),
(26, 'C25: Trabajos de control de calidad, verificación e inspección de materias en curso y en productos terminados del sector', 'TPM', NULL),
(27, 'C26: Conductores o transportistas', 'TPM', NULL),
(28, 'C27: Conductores de carretillas elevadoras', 'TPM', NULL),
(29, 'C28: Operadores de puente-grúa', 'TPM', NULL),
(30, 'C29: Operadores de plataformas elevadores', 'TPM', NULL),
(31, 'C30: Operarios de almacén y logística y aprovisionamiento en los procesos de fabricación', 'TPM', NULL),
(32, 'C31: Conductores de grúas móviles autopropulsadas', 'TPM', NULL),
(33, 'C32 Actividades no expresamente reguladas por este convenio ', 'TPM', NULL),
(34, 'Formacion Inicial', 'TPC', NULL),
(35, 'Nivel básico de prevención en la construcción', 'TPC', NULL),
(36, 'Administrativos', 'TPC', NULL),
(37, 'Delegados de prevención', 'TPC', NULL),
(38, 'Mandos intermedios', 'TPC', NULL),
(39, 'Personal directivo de empresa', 'TPC', NULL),
(40, 'Responsables de obra y técnicos de ejecución', 'TPC', NULL),
(41, 'Albañilería', 'TPC', NULL),
(42, 'Cimentaciones especiales, sondeos y perforaciones', 'TPC', NULL),
(43, 'Colocación de materiales de cubrición', 'TPC', NULL),
(44, 'Construcción y mantenimiento de vías férreas', 'TPC', NULL),
(45, 'Electricidad, montaje y mantenimiento de instalaciones eléctricas de alta y baja tensión', 'TPC', NULL),
(46, 'Encofrados', 'TPC', NULL),
(47, 'Ferrallado', 'TPC', NULL),
(48, 'Fontanería e instalaciones de climatización', 'TPC', NULL),
(49, 'Mantenimiento de maquinaria y vehículos', 'TPC', NULL),
(50, 'Montador de escayola, placas de yeso laminado y asimilados', 'TPC', NULL),
(51, 'Montaje de estructuras tubulares', 'TPC', NULL),
(52, 'Operadores de aparatos elevadores', 'TPC', NULL),
(53, 'Operadores de equipos manuales', 'TPC', NULL),
(54, 'Operadores de vehículos y maquinaria de movimiento de tierras', 'TPC', NULL),
(55, 'Operario de instalaciones temporales de obra y auxiliares: plantas de aglomerado, de hormigón, de machaqueo y clasificación de áridos', 'TPC', NULL),
(56, 'Operario de taller de materiales: piedras industriales, tratamiento o transformación de materiales, canteros y similares', 'TPC', NULL),
(57, 'Pintura', 'TPC', NULL),
(58, 'Revestimientos de yeso', 'TPC', NULL),
(59, 'Revestimientos exteriores', 'TPC', NULL),
(60, 'Solados y alicatados', 'TPC', NULL),
(61, 'Trabajos de aislamiento e impermeabilización', 'TPC', NULL),
(62, 'Trabajos de conservación y explotación de carreteras', 'TPC', NULL),
(63, 'Trabajos de demolición y rehabilitación', 'TPC', NULL),
(64, 'Trabajos de estabilización de explanadas y extendido de firmes', 'TPC', NULL),
(65, 'Trabajos de montaje de prefabricados de hormigón en obra', 'TPC', NULL),
(66, 'Trabajos de redes de abastecimiento y saneamiento y pocería', 'TPC', NULL),
(67, 'Trabajos de soldadura', 'TPC', NULL),
(68, 'Trabajos específicos de ejecución de túneles y sostenimiento de las excavaciones subterráneas y de los taludes', 'TPC', NULL),
(69, 'Trabajos marítimos', 'TPC', NULL),
(70, 'Formación inicial', 'TPCMADERA', NULL),
(71, 'Delegados de prevención', 'TPCMADERA', NULL),
(72, 'Directivos de las Empresas', 'TPCMADERA', NULL),
(73, 'Mandos intermedios', 'TPCMADERA', NULL),
(74, 'Responsables y técnicos de ejecución de la actividad', 'TPCMADERA', NULL),
(75, 'Instalador de elementos de carpintería y mueble', 'TPCMADERA', NULL),
(76, 'Montador de estructuras de madera', 'TPCMADERA', NULL),
(77, 'Instalador de elementos de carpintería y mueble', 'TPCMADERA', NULL),
(78, 'Directivos y gerentes de empresa', 'TPCVIDRIO', NULL),
(79, 'Instalador de rótulos', 'TPCVIDRIO', NULL),
(80, 'Instalador de ventanas y acristalamientos', 'TPCVIDRIO', NULL),
(81, 'PASTELERIA / PANADERIA', 'OTROS', NULL),
(82, 'FRIO INDUSTRIAL NAVAL', 'OTROS', NULL),
(83, 'ELECTRICIDAD INDUSTRIAL NAVAL', 'OTROS', NULL),
(84, 'FRIO INDUSTRIAL / CLIMATIZACION', 'OTROS', NULL),
(85, 'PINTURA NAVAL / METAL', 'OTROS', NULL),
(86, 'PELUQUERIA', 'OTROS', NULL),
(87, 'TECNICO HIGIENICO SANITARIO', 'OTROS', NULL),
(88, 'LABORAL / FISCAL / GESTORIA', 'OTROS', NULL),
(89, 'DINAMICAS PERSONAS MAYORES', 'OTROS', NULL),
(90, 'FIBRA DE CARBONO', 'OTROS', NULL),
(91, 'CARRETILLA ELEVADORA', 'CONSTRUCCIÓN', NULL),
(92, 'PLATAFORMA ELEVADORA', 'CONSTRUCCIÓN', NULL),
(93, 'PUENTE GRUA', 'CONSTRUCCIÓN', NULL),
(94, 'MANIPULADORA TELESCOPICA', 'CONSTRUCCIÓN', NULL),
(95, 'PALA RETROEXCAVADORA', 'CONSTRUCCIÓN', NULL),
(96, 'CAMION GRUA', 'CONSTRUCCIÓN', NULL),
(98, 'CAMION + CAP', 'AUTOESCUELA', '140'),
(99, 'CAP INICIAL', 'AUTOESCUELA', NULL),
(100, 'CAMION INICIAL', 'AUTOESCUELA', NULL),
(101, 'FITOSANITARIOS INICIAL', 'OTROS', NULL),
(102, 'FITOSANITARIOS PUENTE', 'OTROS', NULL),
(103, 'SOCORRISTA', 'OTROS', NULL),
(104, 'HIDRAULICA / NEUMATICA', 'OTROS', NULL),
(105, 'PLACAS SOLARES / ENERGIAS RENOVABLES', 'OTROS', NULL),
(106, 'TASACION INMOBILIARIA', 'OTROS', NULL),
(107, 'COMERCIO INTERNACIONAL / ADUANAS', 'OTROS', NULL),
(108, 'CERRAJERIA', 'OTROS', NULL),
(109, 'COCINA / TAPEO / COCTELERIA', 'OTROS', NULL),
(110, 'CAD / CAM ', 'OTROS', NULL),
(111, 'CNC / FAGOR / FANUC / SIEMENS', 'OTROS', NULL),
(112, 'SOLIDWORKS', 'OTROS', NULL),
(113, 'SKETCHUP / AUTOCAD', 'OTROS', NULL),
(115, 'UNE:CARRETILLA', 'CONSTRUCCIÓN', NULL),
(116, 'UNE: PLATAFORMA', 'CONSTRUCCIÓN', NULL),
(117, 'MONTAJE DE ANDAMIOS', 'CONSTRUCCIÓN', NULL),
(119, 'RETIRADA DE AMIANTO/URALITA', 'CONSTRUCCIÓN', NULL),
(120, 'OPERADOR DE GRUA TORRE', 'CONSTRUCCIÓN', NULL),
(121, '- SOLICITANDO EMPLEADO -', 'OTROS', NULL),
(123, 'BIENESTAR ANIMAL EN EL TRANSPORTE', 'OTROS', '20 HOR'),
(124, 'CONTABILIDAD INICIAL EN EMPRESAS', 'OTROS', '100'),
(126, 'INTELIGENCIA ARTIFICIAL', 'OTROS', NULL),
(127, 'TRABAJOS EN ALTURA', 'CONSTRUCCIÓN', '8'),
(128, 'TRABAJOS DE INSTALACIONES, REPARACIONES, MONTAJES, ESTRUCTURAS METÁLICAS, CERRAJERÍA Y CARPINTERÍA METÁLICA', 'TPC', '6'),
(129, NULL, '--- Seleccione ---', NULL),
(130, 'VEHICULOS ELECTRICOS', 'OTROS', NULL),
(131, 'LIMPIEZA Y DESINFECCIÓN ', 'OTROS', NULL),
(132, 'ESPACIOS CONFINADOS', 'CONSTRUCCIÓN', NULL),
(133, 'MAQUILLAJE', 'OTROS', NULL),
(134, 'MANICURA/PEDICURA', 'OTROS', NULL),
(135, 'MASAJE / TRATAMIENTOS', 'OTROS', NULL),
(137, 'CAP RENOVACIÓN', 'AUTOESCUELA', NULL),
(138, 'ADR RENOVACIÓN', 'AUTOESCUELA', NULL),
(139, 'ADR INICIAL', 'AUTOESCUELA', NULL),
(140, 'DIRECTIVOS Y GERENTES DE EMPRESA', 'TPCVIDREO', NULL),
(141, 'INSTALADOR DE RÓTULOS', 'TPCVIDREO', NULL),
(142, 'INSTALADOR DE VENTANAS Y ACRISTALAMIENTOS', 'TPCVIDREO', NULL);

UPDATE `tipos_cursos` SET `codigo` = 'CONSTRUCCIÓN',`nombre` = 'CONSTRUCCIÓN' WHERE `tipos_cursos`.`tipos_cursos_id` = 3;
UPDATE `listacursos` SET orden = idCurso WHERE idCurso < 34;